<template>
<div>{{msg}}</div>
</template>
<script>
export default {
  props:{
    msg:String
  },
  beforeCreate(){
    console.log('beforeCreate')
  },
  created(){
    console.log('created')
  },
  beforeMount(){
     console.log('beforeMount')
  },
  mounted(){
     console.log('mounted')
  },
  beforeUpdate(){
    console.log('beforeUpdate')
  },
  updated(){
    console.log('updated')
  },
  beforeDestroy(){
      console.log('beforeDestroy')
  },
  destroyed(){
      console.log('destroyed')
  },
}
</script>